// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AttendanceMarkAttendanceData, AttendanceMarkAttendanceResponse, AttendanceListAttendanceData, AttendanceListAttendanceResponse, AttendanceUndoAttendanceData, AttendanceUndoAttendanceResponse, AuthReadCurrentUserResponse, ConsentCreateConsentData, ConsentCreateConsentResponse, ConsentListConsentsData, ConsentListConsentsResponse, ConsentRevokeConsentData, ConsentRevokeConsentResponse, PatientsListPatientsResponse, PatientsEnrollPatientData, PatientsEnrollPatientResponse, PatientsGetPatientData, PatientsGetPatientResponse, PatientsGetClinicalData, PatientsGetClinicalResponse, PatientsGetMmjInfoData, PatientsGetMmjInfoResponse, PrivateCreateUserData, PrivateCreateUserResponse, PrivateDevTokenData, PrivateDevTokenResponse, UsersListUsersData, UsersListUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersGetUserData, UsersGetUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class AttendanceService {
    /**
     * Mark Attendance
     * @param data The data for the request.
     * @param data.requestBody
     * @returns AttendancePublic Successful Response
     * @throws ApiError
     */
    public static markAttendance(data: AttendanceMarkAttendanceData): CancelablePromise<AttendanceMarkAttendanceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/attendance/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Attendance
     * @param data The data for the request.
     * @param data.patientId
     * @param data.encounterId
     * @returns AttendancePublic Successful Response
     * @throws ApiError
     */
    public static listAttendance(data: AttendanceListAttendanceData = {}): CancelablePromise<AttendanceListAttendanceResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/attendance/',
            query: {
                patient_id: data.patientId,
                encounter_id: data.encounterId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Undo Attendance
     * @param data The data for the request.
     * @param data.observationId
     * @returns AttendancePublic Successful Response
     * @throws ApiError
     */
    public static undoAttendance(data: AttendanceUndoAttendanceData): CancelablePromise<AttendanceUndoAttendanceResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/attendance/{observation_id}/undo',
            path: {
                observation_id: data.observationId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class AuthService {
    /**
     * Read Current User
     * Verify token and return current user.
     * @returns AppUserPublic Successful Response
     * @throws ApiError
     */
    public static readCurrentUser(): CancelablePromise<AuthReadCurrentUserResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/auth/me'
        });
    }
}

export class ConsentService {
    /**
     * Create Consent
     * @param data The data for the request.
     * @param data.patientId
     * @param data.requestBody
     * @returns ConsentPublic Successful Response
     * @throws ApiError
     */
    public static createConsent(data: ConsentCreateConsentData): CancelablePromise<ConsentCreateConsentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/patients/{patient_id}/consents/',
            path: {
                patient_id: data.patientId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Consents
     * @param data The data for the request.
     * @param data.patientId
     * @returns ConsentPublic Successful Response
     * @throws ApiError
     */
    public static listConsents(data: ConsentListConsentsData): CancelablePromise<ConsentListConsentsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/patients/{patient_id}/consents/',
            path: {
                patient_id: data.patientId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Revoke Consent
     * @param data The data for the request.
     * @param data.patientId
     * @param data.consentId
     * @returns ConsentPublic Successful Response
     * @throws ApiError
     */
    public static revokeConsent(data: ConsentRevokeConsentData): CancelablePromise<ConsentRevokeConsentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/patients/{patient_id}/consents/{consent_id}/revoke',
            path: {
                patient_id: data.patientId,
                consent_id: data.consentId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PatientsService {
    /**
     * List Patients
     * @returns PatientEnrollResponse Successful Response
     * @throws ApiError
     */
    public static listPatients(): CancelablePromise<PatientsListPatientsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/patients/'
        });
    }
    
    /**
     * Enroll Patient
     * @param data The data for the request.
     * @param data.requestBody
     * @returns PatientEnrollResponse Successful Response
     * @throws ApiError
     */
    public static enrollPatient(data: PatientsEnrollPatientData): CancelablePromise<PatientsEnrollPatientResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/patients/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Patient
     * @param data The data for the request.
     * @param data.patientId
     * @returns PatientEnrollResponse Successful Response
     * @throws ApiError
     */
    public static getPatient(data: PatientsGetPatientData): CancelablePromise<PatientsGetPatientResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/patients/{patient_id}',
            path: {
                patient_id: data.patientId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Clinical
     * @param data The data for the request.
     * @param data.patientId
     * @returns Patient Successful Response
     * @throws ApiError
     */
    public static getClinical(data: PatientsGetClinicalData): CancelablePromise<PatientsGetClinicalResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/patients/{patient_id}/clinical',
            path: {
                patient_id: data.patientId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Mmj Info
     * @param data The data for the request.
     * @param data.patientId
     * @returns MMJInfoResponse Successful Response
     * @throws ApiError
     */
    public static getMmjInfo(data: PatientsGetMmjInfoData): CancelablePromise<PatientsGetMmjInfoResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/patients/{patient_id}/mmj',
            path: {
                patient_id: data.patientId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user (dev only, no auth required).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns AppUserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Dev Token
     * Issue a token for a given user_id. Dev only.
     * @param data The data for the request.
     * @param data.userId
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static devToken(data: PrivateDevTokenData): CancelablePromise<PrivateDevTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/dev-token',
            query: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * List Users
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns AppUserPublic Successful Response
     * @throws ApiError
     */
    public static listUsers(data: UsersListUsersData = {}): CancelablePromise<UsersListUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * @param data The data for the request.
     * @param data.requestBody
     * @returns AppUserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get User
     * @param data The data for the request.
     * @param data.userId
     * @returns AppUserPublic Successful Response
     * @throws ApiError
     */
    public static getUser(data: UsersGetUserData): CancelablePromise<UsersGetUserResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}