// This file is auto-generated by @hey-api/openapi-ts

export type AppUserCreate = {
    fhir_ref?: (string | null);
    role: UserRole;
    display_name?: (string | null);
};

export type AppUserPublic = {
    fhir_ref?: (string | null);
    role: UserRole;
    display_name?: (string | null);
    id: string;
    created_at: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UserRole = 'PATIENT' | 'ADMIN_CANNABIS' | 'PROVIDER' | 'SUPER_USER';

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AuthReadCurrentUserResponse = (AppUserPublic);

export type PrivateCreateUserData = {
    requestBody: AppUserCreate;
};

export type PrivateCreateUserResponse = (AppUserPublic);

export type PrivateDevTokenData = {
    userId: string;
};

export type PrivateDevTokenResponse = (Token);

export type UsersListUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersListUsersResponse = (Array<AppUserPublic>);

export type UsersCreateUserData = {
    requestBody: AppUserCreate;
};

export type UsersCreateUserResponse = (AppUserPublic);

export type UsersGetUserData = {
    userId: string;
};

export type UsersGetUserResponse = (AppUserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);