// This file is auto-generated by @hey-api/openapi-ts

export type AppUserCreate = {
    fhir_ref?: (string | null);
    role: UserRole;
    display_name?: (string | null);
};

export type AppUserPublic = {
    fhir_ref?: (string | null);
    role: UserRole;
    display_name?: (string | null);
    id: string;
    created_at: string;
};

export type AttendanceCreateRequest = {
    patient_id?: (string | null);
    display_name?: (string | null);
    encounter_id: string;
    attended?: boolean;
};

export type AttendancePublic = {
    id: string;
    patient_fhir_ref: string;
    encounter_id: string;
    attended: boolean;
    status: string;
    effective_date_time?: (string | null);
};

export type ConsentCreateRequest = {
    consent_type: ConsentType;
    expires_at?: (string | null);
};

export type ConsentPublic = {
    id: string;
    consent_type: string;
    status: string;
    date_time?: (string | null);
    expires_at?: (string | null);
};

export type ConsentType = 'therapy_participation' | 'location_sharing' | 'recording_ai' | 'mmj_management';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type MMJInfoResponse = {
    display_name: (string | null);
    phone: (string | null);
    recompass_patient_id?: (string | null);
    consent_expires?: (string | null);
};

export type Patient = {
    [key: string]: unknown;
};

export type PatientEnrollRequest = {
    display_name: string;
    phone: string;
};

export type PatientEnrollResponse = {
    id: string;
    display_name: (string | null);
    fhir_ref: string;
    role: UserRole;
    created_at: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UserRole = 'PATIENT' | 'ADMIN_CANNABIS' | 'PROVIDER' | 'SUPER_USER';

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AttendanceMarkAttendanceData = {
    requestBody: AttendanceCreateRequest;
};

export type AttendanceMarkAttendanceResponse = (AttendancePublic);

export type AttendanceListAttendanceData = {
    encounterId?: (string | null);
    patientId?: (string | null);
};

export type AttendanceListAttendanceResponse = (Array<AttendancePublic>);

export type AttendanceUndoAttendanceData = {
    observationId: string;
};

export type AttendanceUndoAttendanceResponse = (AttendancePublic);

export type AuthReadCurrentUserResponse = (AppUserPublic);

export type ConsentCreateConsentData = {
    patientId: string;
    requestBody: ConsentCreateRequest;
};

export type ConsentCreateConsentResponse = (ConsentPublic);

export type ConsentListConsentsData = {
    patientId: string;
};

export type ConsentListConsentsResponse = (Array<ConsentPublic>);

export type ConsentRevokeConsentData = {
    consentId: string;
    patientId: string;
};

export type ConsentRevokeConsentResponse = (ConsentPublic);

export type PatientsListPatientsResponse = (Array<PatientEnrollResponse>);

export type PatientsEnrollPatientData = {
    requestBody: PatientEnrollRequest;
};

export type PatientsEnrollPatientResponse = (PatientEnrollResponse);

export type PatientsGetPatientData = {
    patientId: string;
};

export type PatientsGetPatientResponse = (PatientEnrollResponse);

export type PatientsGetClinicalData = {
    patientId: string;
};

export type PatientsGetClinicalResponse = (Patient);

export type PatientsGetMmjInfoData = {
    patientId: string;
};

export type PatientsGetMmjInfoResponse = (MMJInfoResponse);

export type PrivateCreateUserData = {
    requestBody: AppUserCreate;
};

export type PrivateCreateUserResponse = (AppUserPublic);

export type PrivateDevTokenData = {
    userId: string;
};

export type PrivateDevTokenResponse = (Token);

export type UsersListUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersListUsersResponse = (Array<AppUserPublic>);

export type UsersCreateUserData = {
    requestBody: AppUserCreate;
};

export type UsersCreateUserResponse = (AppUserPublic);

export type UsersGetUserData = {
    userId: string;
};

export type UsersGetUserResponse = (AppUserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);