"""text_blast sent_by set null on delete

Revision ID: 03bdc77ea3e5
Revises: 31417826c710
Create Date: 2026-03-29 20:04:49.313026

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '03bdc77ea3e5'
down_revision = '31417826c710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('text_blasts', 'sent_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('text_blasts_sent_by_fkey'), 'text_blasts', type_='foreignkey')
    op.create_foreign_key(None, 'text_blasts', 'app_users', ['sent_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'text_blasts', type_='foreignkey')
    op.create_foreign_key(op.f('text_blasts_sent_by_fkey'), 'text_blasts', 'app_users', ['sent_by'], ['id'])
    op.alter_column('text_blasts', 'sent_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
